Repository commercelayer/app-sku-lists, pull requests merged in 2024-06, with the labels that each got.

#18 Fix SKUList edit form
  packages/app/src/components/ListItemSku.tsx
  packages/app/src/components/SkuListForm/SkuListForm.tsx
  packages/app/src/components/SkuListForm/schema.ts
  packages/app/src/components/SkuListForm/utils.ts
  packages/app/src/hooks/useSkuListDetails.tsx
  packages/app/src/hooks/useSkuListItems.tsx
  packages/app/src/hooks/useUpdateSkuList.tsx
  packages/app/src/pages/SkuListDetails.tsx
Labels: bug

#19 v1.0.8
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#21 Export 'Main' component as default
  packages/app/src/main.tsx
Labels: enhancement, ignore-for-release
